spring.application.name=gateway

server.port=8080

jwt.secret=7hn325CSL9irVF8m2nN4HZOgvGSopeUeNw8G/UhON+A=
gateway.secret=trilhadeaprendizadoapims-gateway

cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3001,http://127.0.0.1:3000
